# Form implementation generated from reading ui file 'fullSCR.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fullSCR(object):
    def setupUi(self, fullSCR):
        fullSCR.setObjectName("fullSCR")
        fullSCR.resize(1978, 1223)
        fullSCR.setMinimumSize(QtCore.QSize(1920, 1080))
        fullSCR.setStyleSheet("background-color:#081a3a;\n"
"color: #5DBE06;")
        self.centralwidget = QtWidgets.QWidget(parent=fullSCR)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(1960, 1161))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        fullSCR.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=fullSCR)
        self.statusbar.setObjectName("statusbar")
        fullSCR.setStatusBar(self.statusbar)

        self.retranslateUi(fullSCR)
        QtCore.QMetaObject.connectSlotsByName(fullSCR)

    def retranslateUi(self, fullSCR):
        _translate = QtCore.QCoreApplication.translate
        fullSCR.setWindowTitle(_translate("fullSCR", "MainWindow"))
        self.comboBox.setItemText(0, _translate("fullSCR", "Меню"))
        self.comboBox.setItemText(1, _translate("fullSCR", "Полный контроль"))
        self.comboBox.setItemText(2, _translate("fullSCR", "Передача файлов"))
        self.comboBox.setItemText(3, _translate("fullSCR", "Управление питанием"))
        self.comboBox.setItemText(4, _translate("fullSCR", "Терминал"))
        self.comboBox.setItemText(5, _translate("fullSCR", "Кейлоггер"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fullSCR = QtWidgets.QMainWindow()
    ui = Ui_fullSCR()
    ui.setupUi(fullSCR)
    fullSCR.show()
    sys.exit(app.exec())
